config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



  root 'welcome#index'
  get '/etfs/:id', to: 'etfs#show', as: 'etf'
  get '/search', to: 'searches#index', as: 'search'
  get '/search/new', to: 'searches#new', as: 'new_search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  require 'csv'
  require 'nokogiri'
end

app/models/country_weight.rb
class CountryWeight < ApplicationRecord
  belongs_to :etf

end

app/models/etf.rb
class Etf < ApplicationRecord
  has_many :top_holdings
  has_many :sector_allocations
  has_many :country_weights
  has_many :searches

  require 'rubygems'
  require 'nokogiri'

  def self.find_by_ticker(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

  def to_csv
    attributes = %w{name amount}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      self.top_holdings.each do |top_holding|
        csv << attributes.map{ |attr| top_holding.send(attr) }
      end

      if !sector_allocations.empty?
        csv << [" "]
        csv << ["sector", "weight(%)"]

        self.sector_allocations.each do |sector_allocation|
          csv << attributes.map{ |attr| sector_allocation.send(attr) }
        end
      end

      if !country_weights.empty?
        csv << [" "]
        csv << ["country", "weight(%)"]

        self.country_weights.each do |country_weight|
          csv << attributes.map{ |attr| country_weight.send(attr) }
        end
      end
    end
  end

end

app/models/scraper.rb
class Scraper < ApplicationRecord
  require 'mechanize'

  BASE_URL="https://www.spdrs.com/product/fund.seam?ticker="

  def self.new_from_lookup(ticker_symbol)
    query_url = BASE_URL+ticker_symbol
    @agent = Mechanize.new
    page = @agent.get(query_url)
    query_check = page.css('title').text
    if (query_check == "SPDR: SYSTEM ERROR")
      nil
    else
      self.etf_from_scrape(ticker_symbol, page)
    end
  end

  def self.etf_from_scrape(ticker_symbol, page)
    fund_name = page.css('h1').text.strip
    fund_objective = page.css('.overview.tab_section').css('.col2s.leftm').css('p').first.text
    @etf = Etf.create(ticker: ticker_symbol, name: fund_name, objective: fund_objective)
    self.etf_holdings_from_scrape(page, @etf.id)
    @etf
  end

  def self.etf_holdings_from_scrape(page, etf_id)
    self.top_holdings(page, etf_id)
    self.country_weights(page, etf_id)
    self.sector_allocation(page, etf_id)
  end

  def self.top_holdings(page, etf_id)
    fund_holdings_array = page.css('#FUND_TOP_TEN_HOLDINGS').css('tr')[1...10]
    fund_holdings_array.each do |holding|
      holding_name = holding.css('.label').text
      holding_amount = holding.css('.data')[-1].text.gsub!(/,/,'').to_i
      TopHolding.create(name: holding_name, amount: holding_amount, etf_id: etf_id)
    end
  end

  def self.country_weights(page, etf_id)
    country_html_fragment = page.css('.holdings').css('.sect')[-1]
    country_allocation_table_rows = country_html_fragment.css('tr')
    country_allocation_table_rows.each do |row|
      country_name = row.css('.label').text
      country_amount = row.css('.data').text.to_f
      CountryWeight.create(name: country_name, amount: country_amount, etf_id: etf_id)
    end
  end

  def self.sector_allocation(page, etf_id)
    sectors_html_fragment = page.css('#SectorsAllocChart').text
    xml_page = Nokogiri::XML(sectors_html_fragment)
    sector_allocation_table_rows = xml_page.css('attribute')
    sector_allocation_table_rows.each do |row|
      sector_amount = row.css('value').text.to_f
      sector_name = row.css('label').text
      SectorAllocation.create(name: sector_name, amount: sector_amount, etf_id: etf_id)
    end
  end

end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user
  belongs_to :etf

end

app/models/sector_allocation.rb
class SectorAllocation < ApplicationRecord
  belongs_to :etf


end

app/models/top_holding.rb
class TopHolding < ApplicationRecord
  belongs_to :etf

end

app/models/user.rb
class User < ApplicationRecord
  has_many :searches
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #authenticate_user! part of devise library
  before_action :authenticate_user!

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/etfs_controller.rb
class EtfsController < ApplicationController

  def show
    @etf = Etf.find(params[:id])
    @top_holdings = @etf.top_holdings.order(amount: :desc)
    @country_weights = @etf.country_weights.order(amount: :desc)
    @sector_allocations = @etf.sector_allocations.order(amount: :desc)

    #this allows csv files to be downloaded by appending .csv to end of the URL. this happens when users click the download button on the show page. 
    respond_to do |format|
      format.html
      format.csv { send_data @etf.to_csv, filename: "etf-#{@etf.ticker.upcase}-#{Date.today}.csv" }
    end
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  skip_before_action :verify_authenticity_token



  def new
    @etf = Etf.find_by_ticker(etf_params)
    #explanation ||= if @etf = nil, then set @etf = Scraper.new_from_lookup
    #IE, if the ETF is not in the database, scrape for it.
    @etf ||= Scraper.new_from_lookup(etf_params)
    if @etf
      #only creates a valid search record if an ETF is found. Each search belongs to an etf so the search#index action can generate clickable links to each etf#show page.
      @search = Search.create(ticker: etf_params, user_id: current_user.id, etf_id: @etf.id)
    else
      flash[:danger] = "#{params[:etf]} could not be found"
    end
    redirect_to window_location
  end

  def index
    @user_searches = current_user.searches.order(created_at: :desc).limit(10)
  end

  def etf_params
   @etf_params ||= params[:etf].to_s.upcase
  end

  def window_location
    #rerender search page if the etf cannot be found in db or scraped.
   return etf_path(@etf) if @etf.present?

   search_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/etfs/_lookup.html.erb
<div id="etf-lookup">
    <h3>Search for ETFS by ticker symbol</h3>
    <%= form_tag search_etfs_path, remote: true, method: :get, id: 'etf-lookup-form' do %>
    <div class="form-group row no-padding text-center col -md-12">
      <div class="col-md-10">
        <%= text_field_tag :etf, params[:etf], placeholder: "ETF ticker symbol EX: SPY", autofocus: true, class: 'form-control search-box input-lg' %>
      </div>
      <div class='col-md-2'>
        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
          <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Lookup an ETF
        <% end %>
      </div>
    </div>
    <% end %>
</div>

app/views/etfs/show.html.erb
<div class="container">
  <div class=row id="header" align="center">
    <h1><%= @etf.name %></h1>
    <p><%=@etf.objective %></p>
    <a href="<%= @etf.id %>.csv" class="btn btn-default">Download Data as CSV</a>
  </div>
  <% if !@top_holdings.empty? %>
    <div class="row" id="top-holdings">
      <h2 align="center">Fund Top 10 Holdings</h2>
      <div class="col-md-6">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Holding</th>
              <th>Shares</th>
            </tr>
          </thead>
          <tbody>
            <% @top_holdings.each do |holding| %>
            <tr>
              <td><%= holding.name %></td>
              <td><%= holding.amount %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-md-6">
        <%= bar_chart (Hash[@top_holdings.map {|top_holding| [top_holding.name, top_holding.amount]}]), id: "top-holdings-chart", 'height': '368px', library: {vAxis:{title: "Holdings", titleTextStyle:{italic: false}}, hAxis:{title: "Shares", titleTextStyle:{italic: false}}, chartArea: {top:10,width:'70%',height:'80%'}}%>
      </div>
    </div>
  <% end %>
</br>
  <% if !@sector_allocations.empty? %>
    <div class="row" id="sector-allocations">
      <h2 align="center">Fund Sector Allocations</h2>
      <div class="col-md-6">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Sector</th>
              <th>Amount</th>
            </tr>
          </thead>
          <tbody>
            <% @sector_allocations.each do |sector| %>
            <tr>
              <td><%= sector.name %></td>
              <td><%= sector.amount.to_s + " %" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-md-6">
        <%= pie_chart (Hash[@sector_allocations.map {|sector_allocation| [sector_allocation.name, sector_allocation.amount]}]), id: "sector-allocations-chart", 'height': '368px', library: {chartArea: {top:30,width:'100%',height:'100%'}} %>
      </div>
    </div>
  <% end %>
</br>
</br>
  <% if (@country_weights.count > 2)  %>
    <div class="row" id="country-weights">
      <h2 align="center">Fund Country Weights</h2>
      <div class="col-md-6">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Sector</th>
              <th>Amount</th>
            </tr>
          </thead>
          <tbody>
            <% @country_weights.each do |country_weight| %>
            <tr>
              <td><%= country_weight.name %></td>
              <td><%= country_weight.amount.to_s + " %" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-md-6">
        <%= pie_chart (Hash[@country_weights.map {|country_weight| [country_weight.name, country_weight.amount]}]), id: "country-weights-chart", 'height': '368px', library: {chartArea: {top:30,width:'100%',height:'100%'}}%>
      </div>
    </div>
  <% end %>
</div>
</br>

app/views/layouts/_navigation.html.erb
    <nav class="navbar navbar-default" id="navbar-default">
      <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "ETF Summary", root_path, class: "navbar-brand", id: "logo" %>
    </div>


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%if current_user%>
          <li><%= link_to "Search ETFs", search_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%=link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%=link_to "Login", new_user_session_path %></li>
          <li><%=link_to "Sign Up", new_user_registration_path %></li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "EtfData" %></title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
    <%= stylesheet_link_tag 'https://yandex.st/bootstrap/3.1.1/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://yandex.st/bootstrap/3.1.1/js/bootstrap.min.js' %>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
<%= render 'layouts/navigation' %>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
  </body>
</html>

app/views/searches/_lookup.html.erb
<div id="etf-lookup">
    <h3>Search for ETFS by ticker symbol</h3>
    <%= form_tag new_search_path, method: :get, id: 'etf-lookup-form' do %>
    <div class="form-group row no-padding text-center col -md-12">
      <div class="col-md-10">
        <%= text_field_tag :etf, params[:etf], placeholder: "ETF ticker symbol EX: SPY", autofocus: true, class: 'form-control search-box input-lg', style: "text-transform: uppercase" %>
      </div>
      <div class='col-md-2'>
        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
          <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Lookup an ETF
        <% end %>
      </div>
    </div>
    <% end %>
</div>

app/views/searches/index.html.erb
<%= render 'searches/lookup' %>

<div class="container">
  <table class="table table-striped" id="user-searches">
    <thead>
      <th>Ticker Symbol</th>
      <th>Last Searched</th>
    </thead>
    <tbody>
    <% @user_searches.each do |search| %>
      <tr>
        <td><a href="../etfs/<%=search.etf_id%>"><%=search.ticker%></a></td>
        <td><%=search.created_at.strftime("Last searched %m/%d/%y") %>
      </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/welcome/index.html.erb
<div class="center jumbotron">
  <div class="home-content">
    <h1>Welcome to ETF Data Visualizer</h1>
    <p> Presenting ETF Data pulled from State Street Advisors</p>
    <% if !current_user %>
     <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-lg btn-xlarge" %>
     <%= link_to "Sign In", new_user_session_path, class: "btn btn-success btn-lg btn-xlarge" %>
    <% elsif current_user  %>
      <%= link_to "Search ETFs", search_path, class: "btn btn-success btn-lg btn-xlarge" %>
    <% end %>
  </div>
</div>